vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        media_object:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m/d'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 